name: oneaction

on:
  pull_request:
    branches:
      - main
#   push:
#     branches:
#       - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a one-liner script
        run: echo Hello, world!

      - name: Run a one-liner script
        run: echo Hello, world!
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2
      - name: Run a one-liner script
        run: echo Hello, world!